### ISSUE TITLE
When I restart Espanso wants to migrate my config from V1 to V2, it fails.

### ISSUE THREAD

**Issue by KyleSnodgrass** [federico-terzi/espanso#1059]
**Describe the bug**
I migrated from V1 to V2. 
Migration was successful.
After every restart espanso thinks I have an old configuration setup and attempts migration again.

**To Reproduce**
1. migrate from V1 to V2
2. reboot and see if espanso think the migration occured successfully.

**Expected behavior**
I expect that the migration would only need to occur once. 
Seems there must be something in the config that either not migrated properly or an internal setting that does not set the migration as having completed successfully. 

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
```
08:03:47 [migrate(1276)] [ERROR] thread 'main' panicked at 'an error occurred while converting the configuration: Path "/var/folders/0h/6b2645qd0bndqh_x_0zzw3km0000gn/T/espanso-migrate-out.LG4izhn1Gswg/out/config/default.yml" is exist': espanso/src/cli/migrate.rs:131
08:03:47 [migrate(1276)] [ERROR] ERROR: 'main' panicked at 'an error occurred while converting the configuration: Path "/var/folders/0h/6b2645qd0bndqh_x_0zzw3km0000gn/T/espanso-migrate-out.LG4izhn1Gswg/out/config/default.yml" is exist': espanso/src/cli/migrate.rs:131
```

**Logs**
```
08:00:30 [worker(34183)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
08:00:32 [worker(34183)] [INFO] secure input has been disabled
08:00:44 [worker(34183)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
08:03:46 [migrate(1276)] [INFO] reading configs from: "/Users/ksnodgra/Library/Preferences/espanso"
08:03:46 [migrate(1276)] [INFO] reading packages from: "/Users/ksnodgra/Library/Application Support/espanso/packages"
08:03:46 [migrate(1276)] [INFO] using runtime dir: "/Users/ksnodgra/Library/Application Support/espanso"
08:03:46 [migrate(1276)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
08:03:46 [migrate(1276)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
08:03:46 [migrate(1276)] [INFO] --- MIGRATION STARTED ---
08:03:46 [migrate(1276)] [INFO] backing up the configuration directory: '/Users/ksnodgra/Library/Preferences/espanso'
08:03:46 [migrate(1276)] [INFO]  -> into this folder: '/Users/ksnodgra/Documents/espanso-migrate-backup-6'
08:03:46 [migrate(1276)] [INFO] backup completed!
08:03:46 [migrate(1276)] [INFO] converting the configuration...
08:03:47 [migrate(1276)] [ERROR] thread 'main' panicked at 'an error occurred while converting the configuration: Path "/var/folders/0h/6b2645qd0bndqh_x_0zzw3km0000gn/T/espanso-migrate-out.LG4izhn1Gswg/out/config/default.yml" is exist': espanso/src/cli/migrate.rs:131
08:03:47 [migrate(1276)] [ERROR] ERROR: 'main' panicked at 'an error occurred while converting the configuration: Path "/var/folders/0h/6b2645qd0bndqh_x_0zzw3km0000gn/T/espanso-migrate-out.LG4izhn1Gswg/out/config/default.yml" is exist': espanso/src/cli/migrate.rs:131```

Additionally, I can see that indeed the files default.yml does exist:
```
(base)  /var/folders/0h/6b2645qd0bndqh_x_0zzw3km0000gn/T/espanso-migrate-out.LG4izhn1Gswg/out/ tree
.
├── config
│   └── default.yml
└── match
    ├── base.yml
    └── match
......
```
**Workaround**
- I can workaround this by removing the additional `default.yml` file that's created in the main directory `/Users/ksnodgra/Library/Preferences/espanso` this file has initial data in it as though you were just getting started. 
- Once this file is removed espanso will start up as expected without attempting to migrate the data again. 
- My default.yml file remains in the `config` folder.


**Setup information**
- OS: What OS are you using? MAC 12.3 (21E230)
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
```
espanso 2.1.4-beta
```

**Comment by federico-terzi** [comment]
Hey @KyleSnodgrass,

I'm sorry you experienced this problem! A couple of questions:
* Did you uninstall Espanso v1 beforehand? Perhaps, you're running two Espanso instances at the same time without noticing (though it's unlikely)
* Are you using any symlink in your configuration directory?
* Could you please run `ls -laR /Users/ksnodgra/Library/Preferences/espanso` and post the output here?

Cheers :)

**Comment by KyleSnodgrass** [comment]
Hey Federico,
  I did uninstall V1 before installing V2. I followed the instructions on the website to the best of my ability.
![image](https://user-images.githubusercontent.com/49624074/161973029-5fd6f59b-5f3a-4ea8-a436-7298bc280dee.png)

Also it is worth noting that I stopped espanso and started it again and it runs 3 PIDs which doesn't seem too far out of wack to me, but I'll let you be the judge of that.

So far as the out put of the linux command, I think I'm gonna have to look that over before pasting the output. I want to be sure there's no personal information in there. I did validate that there are no symlinks involved.

Thanks for your help.

**Comment by federico-terzi** [comment]
@KyleSnodgrass Thanks! The 3 processes look ok

I don't have other ideas at the moment, but we'll investigate!

**Comment by KyleSnodgrass** [comment]
Thanks! I recently deleted and restored my library. We’ll see if that does
anything for when I reboot.

**Comment by camrodam** [comment]
Still had this same issue on MacOS Monterey 12.5.1 - workaround mentioned also still solves the issue.

**Comment by karstengresch** [comment]
Thanks and kudos to @KyleSnodgrass for the workaround (deleting `default.yml` in espanso-config root).

IMHO it'd be useful to document it under "Troubleshooting".

**Comment by fharper** [comment]
Deleting `default.yml` doesn't fix it for me, still having issues migrating. I ran on compatibility mode for months, but for whatever reason Espanso stopped working, so I decided to go through the process or migrating in case it is why it's running but not working. Anyway, the latter is a separate issue, just trying to migrate now, so I think I'll just manually update the content after install a fresh copy of Espanso.

**Comment by fharper** [comment]
Doing the process manually (updating manually based on https://espanso.org/docs/migration/what_changed/ + moving the files to the new location myself) did the trick.
