### ISSUE TITLE
I get additional ] at the 2nd Position and Position of Cursor jumps

### ISSUE THREAD

**Issue by ghost** [federico-terzi/espanso#1801]
**Describe the bug**
I configured a match as follows:
`  - trigger: ":rh"
    replace: "#[[Rabbit Hole]]"`
If I am now writing in Logseq in a sentence something like `19:30 Got drawn into another :rh` I will get `1]9:30 Got drawn into another #[[Rabbit Hole]]`

**To Reproduce**
1. Configure the match as defined above
2. Install Logseq
3. Start with a new line
4. Write some words 

**Expected behavior**

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem
18:56:56 [daemon(11004)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
18:56:56 [daemon(11004)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
18:56:56 [daemon(11004)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
18:56:56 [daemon(11004)] [INFO] system info: Windows v10 (19045) - kernel:19045
18:56:56 [daemon(11004)] [INFO] watching for changes in path: "XXX\\AppData\\Roaming\\espanso"
18:56:56 [daemon(11004)] [INFO] espanso version: 2.2.1
18:56:56 [daemon(11004)] [INFO] spawning the worker process...
18:56:56 [daemon(11004)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
18:56:56 [worker(18584)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
18:56:56 [worker(18584)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
18:56:56 [worker(18584)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
18:56:56 [worker(18584)] [INFO] system info: Windows v10 (19045) - kernel:19045
18:56:56 [worker(18584)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
18:56:56 [worker(18584)] [INFO] using Win32AppInfoProvider
18:56:56 [worker(18584)] [INFO] monitoring the status of the daemon process
18:56:56 [worker(18584)] [INFO] using Win32Source
18:56:56 [worker(18584)] [INFO] using Win32Injector
18:56:56 [worker(18584)] [INFO] using Win32Clipboard
18:56:58 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
18:56:58 [worker(18584)] [INFO] engine eventloop has terminated, propagating exit event...
18:56:58 [worker(18584)] [INFO] waiting for engine exit mode...
18:56:58 [worker(18584)] [INFO] exiting worker process...
18:56:58 [daemon(11004)] [INFO] spawning the worker process...
18:56:58 [worker(12592)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
18:56:58 [worker(12592)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
18:56:58 [worker(12592)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
18:56:58 [worker(12592)] [INFO] system info: Windows v10 (19045) - kernel:19045
18:56:58 [worker(12592)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
18:56:58 [worker(12592)] [INFO] using Win32AppInfoProvider
18:56:58 [worker(12592)] [INFO] monitoring the status of the daemon process
18:56:58 [worker(12592)] [INFO] using Win32Source
18:56:58 [worker(12592)] [INFO] using Win32Injector
18:56:58 [worker(12592)] [INFO] using Win32Clipboard
18:59:52 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
18:59:52 [worker(12592)] [INFO] engine eventloop has terminated, propagating exit event...
18:59:52 [worker(12592)] [INFO] waiting for engine exit mode...
18:59:52 [worker(12592)] [INFO] exiting worker process...
18:59:52 [daemon(11004)] [INFO] spawning the worker process...
18:59:52 [worker(15480)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
18:59:52 [worker(15480)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
18:59:52 [worker(15480)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
18:59:52 [worker(15480)] [INFO] system info: Windows v10 (19045) - kernel:19045
18:59:52 [worker(15480)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
18:59:52 [worker(15480)] [INFO] using Win32AppInfoProvider
18:59:52 [worker(15480)] [INFO] monitoring the status of the daemon process
18:59:52 [worker(15480)] [INFO] using Win32Source
18:59:52 [worker(15480)] [INFO] using Win32Injector
18:59:52 [worker(15480)] [INFO] using Win32Clipboard
19:03:46 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
19:03:46 [worker(15480)] [INFO] engine eventloop has terminated, propagating exit event...
19:03:46 [worker(15480)] [ERROR] thread 'detect thread' panicked at 'unable to send to the source channel: "SendError(..)"': espanso\src\cli\worker\engine\funnel\mod.rs:104
19:03:46 [worker(15480)] [ERROR] Win32Source destruction returned non-zero code
19:03:46 [worker(15480)] [INFO] waiting for engine exit mode...
19:03:46 [worker(15480)] [INFO] exiting worker process...
19:03:46 [daemon(11004)] [INFO] spawning the worker process...
19:03:46 [worker(13720)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
19:03:46 [worker(13720)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
19:03:46 [worker(13720)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
19:03:46 [worker(13720)] [INFO] system info: Windows v10 (19045) - kernel:19045
19:03:46 [worker(13720)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
19:03:46 [worker(13720)] [INFO] using Win32AppInfoProvider
19:03:46 [worker(13720)] [INFO] monitoring the status of the daemon process
19:03:46 [worker(13720)] [INFO] using Win32Source
19:03:46 [worker(13720)] [INFO] using Win32Injector
19:03:46 [worker(13720)] [INFO] using Win32Clipboard
19:04:00 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
19:04:00 [worker(13720)] [INFO] engine eventloop has terminated, propagating exit event...
19:04:00 [worker(13720)] [INFO] waiting for engine exit mode...
19:04:00 [worker(13720)] [INFO] exiting worker process...
19:04:00 [daemon(11004)] [INFO] spawning the worker process...
19:04:00 [worker(15628)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
19:04:00 [worker(15628)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
19:04:00 [worker(15628)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
19:04:00 [worker(15628)] [INFO] system info: Windows v10 (19045) - kernel:19045
19:04:00 [worker(15628)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
19:04:00 [worker(15628)] [INFO] using Win32AppInfoProvider
19:04:00 [worker(15628)] [INFO] monitoring the status of the daemon process
19:04:00 [worker(15628)] [INFO] using Win32Source
19:04:00 [worker(15628)] [INFO] using Win32Injector
19:04:00 [worker(15628)] [INFO] using Win32Clipboard
19:23:11 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
19:23:11 [worker(15628)] [INFO] engine eventloop has terminated, propagating exit event...
19:23:11 [worker(15628)] [INFO] waiting for engine exit mode...
19:23:11 [worker(15628)] [INFO] exiting worker process...
19:23:11 [daemon(11004)] [INFO] spawning the worker process...
19:23:11 [worker(18292)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
19:23:11 [worker(18292)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
19:23:11 [worker(18292)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
19:23:11 [worker(18292)] [INFO] system info: Windows v10 (19045) - kernel:19045
19:23:11 [worker(18292)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
19:23:11 [worker(18292)] [INFO] using Win32AppInfoProvider
19:23:11 [worker(18292)] [INFO] monitoring the status of the daemon process
19:23:11 [worker(18292)] [INFO] using Win32Source
19:23:11 [worker(18292)] [INFO] using Win32Injector
19:23:11 [worker(18292)] [INFO] using Win32Clipboard
19:23:41 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
19:23:41 [worker(18292)] [INFO] engine eventloop has terminated, propagating exit event...
19:23:41 [worker(18292)] [INFO] waiting for engine exit mode...
19:23:41 [worker(18292)] [INFO] exiting worker process...
19:23:42 [daemon(11004)] [INFO] spawning the worker process...
19:23:42 [worker(18100)] [INFO] reading configs from: "XXX\\AppData\\Roaming\\espanso"
19:23:42 [worker(18100)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
19:23:42 [worker(18100)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
19:23:42 [worker(18100)] [INFO] system info: Windows v10 (19045) - kernel:19045
19:23:42 [worker(18100)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
19:23:42 [worker(18100)] [INFO] using Win32AppInfoProvider
19:23:42 [worker(18100)] [INFO] monitoring the status of the daemon process
19:23:42 [worker(18100)] [INFO] using Win32Source
19:23:42 [worker(18100)] [INFO] using Win32Injector
19:23:42 [worker(18100)] [INFO] using Win32Clipboard
19:27:44 [daemon(11004)] [INFO] configuration change detected, restarting worker process...
19:27:44 [worker(18100)] [INFO] engine eventloop has terminated, propagating exit event...
19:27:44 [worker(18100)] [ERROR] thread 'detect thread' panicked at 'unable to send to the source channel: "SendError(..)"': espanso\src\cli\worker\engine\funnel\mod.rs:104
19:27:44 [worker(18100)] [ERROR] Win32Source destruction returned non-zero code
19:27:44 [worker(18100)] [INFO] waiting for engine exit mode...
19:27:44 [worker(18100)] [INFO] exiting worker process...
19:27:44 [daemon(11004)] [INFO] spawning the worker process...
19:27:45 [worker(16636)] [INFO] reading configs from: "XXXXXX\\AppData\\Roaming\\espanso"
19:27:45 [worker(16636)] [INFO] reading packages from: "XXX\\AppData\\Roaming\\espanso\\match\\packages"
19:27:45 [worker(16636)] [INFO] using runtime dir: "XXX\\AppData\\Local\\espanso"
19:27:45 [worker(16636)] [INFO] system info: Windows v10 (19045) - kernel:19045
19:27:45 [worker(16636)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
19:27:45 [worker(16636)] [INFO] using Win32AppInfoProvider
19:27:45 [worker(16636)] [INFO] monitoring the status of the daemon process
19:27:45 [worker(16636)] [INFO] using Win32Source
19:27:45 [worker(16636)] [INFO] using Win32Injector
19:27:45 [worker(16636)] [INFO] using Win32Clipboard
 

**Setup information**
- OS: What OS are you using? Windows 10
- Version: 2.2.1

**Comment by smeech** [comment]
I find most of these problems occur using the `Inject` mechanism within text editors.

Try adding one of the undocumented options: `force_mode: clipboard` (as opposed to `keys`), to your script. e.g.:
```
  - trigger: ":rh" 
    replace: "#[[Rabbit Hole]]"
    force_mode: clipboard
```
If it works, it may be worth adding an [app-specific configuration](https://espanso.org/docs/configuration/app-specific-configurations/) for Logseq including the line `backend: Clipboard` instead, so that it applies to all your expansions in that program. 

If you end up accumulating a lot of app-specific configurations for this problem, it may be simpler to add the `backend: Clipboard` line to your `default.yml` and have fewer app-specific configurations with `backend: Auto` for the remainder.
