### ISSUE TITLE
unable to start service: timed out when keyboard layout includes nodeadkeys

### ISSUE THREAD

**Issue by jbaesner** [federico-terzi/espanso#1868]
**Describe the bug**
When using the keyboard layout `de+nodeadkeys`, the espanso service does not start with:

_unable to start service: timed out_

The output of `espanso -vv worker` in this case is:

```
09:56:40 [worker(93851)] [DEBUG] (1) espanso_path: detected config directory in $HOME/.config/espanso
09:56:40 [worker(93851)] [DEBUG] (1) espanso_path: detected default runtime dir: "/home/user/.cache/espanso"
09:56:40 [worker(93851)] [DEBUG] (1) espanso_path: detected default packages dir: "/home/user/.config/espanso/match/packages"
09:56:40 [worker(93851)] [INFO] reading configs from: "/home/user/.config/espanso"
09:56:40 [worker(93851)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
09:56:40 [worker(93851)] [INFO] using runtime dir: "/home/user/.cache/espanso"
09:56:40 [worker(93851)] [INFO] system info: Fedora Linux v37 - kernel: 6.1.7-200.fc37.x86_64
09:56:40 [worker(93851)] [DEBUG] (1) espanso_config::config::store: loaded default config at path: "/home/user/.config/espanso/config/default.yml"
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'alacritty_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'emacs_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'gedit_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'generic_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'kitty_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'konsole_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'libreoffice_writer_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'simple_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'simple_terminal_2_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'terminator_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'termite_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'thunderbird_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'tilix_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'urxvt_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'xterm_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'yakuake_terminal_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::patch::config_store: skipping 'virtualbox_x11' patch
09:56:40 [worker(93851)] [DEBUG] (1) espanso::cli::worker: starting with start-reason = None
09:56:40 [worker(93851)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/user/.cache/espanso/iconv2.png"', as it's already present
09:56:40 [worker(93851)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/user/.cache/espanso/search.png"', as it's already present
09:56:40 [worker(93851)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/user/.cache/espanso/icon_no_background.png"', as it's already present
09:56:40 [worker(93851)] [INFO] binded to IPC unix socket: /home/user/.cache/espanso/espansoworkerv2.sock
09:56:40 [worker(93851)] [INFO] using WaylandAppInfoProvider
09:56:40 [worker(93851)] [DEBUG] (2) espanso::cli::worker::engine: using linux capabilities to grant permissions needed by EVDEV backend
09:56:40 [worker(93851)] [DEBUG] (2) espanso::cli::worker::engine: successfully granted permissions using capabilities
09:56:40 [worker(93851)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de+nodeadkeys, V=, O=]
09:56:40 [worker(93851)] [INFO] using EVDEVSource
xkbcommon: ERROR: Couldn't find file "symbols/nodeadkeys" in include paths
xkbcommon: ERROR: 1 include paths searched:
xkbcommon: ERROR: 	/usr/share/X11/xkb
xkbcommon: ERROR: 1 include paths could not be added:
xkbcommon: ERROR: 	/etc/xkb
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
09:56:40 [worker(93851)] [ERROR] thread 'detect thread' panicked at 'unable to create xkb keymap: could not create xkb keymap': espanso-detect/src/evdev/mod.rs:114
09:56:40 [worker(93851)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
09:56:40 [worker(93851)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
09:56:40 [worker(93851)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
```

**To Reproduce**
1. Follow the steps to _Install on Linux_ for _Wayland_, meaning _Manual  compilation_
2. Start the service while having the keyboard layout `German (no dead keys)` enabled
3. See the service is *not* starting

**Expected behavior**
Starting the espanso service should work fine even with `German (no dead keys)` enabled

**Screenshots**
See bug description.

**Logs**
```
$ espanso log
10:21:01 [daemon(107485)] [INFO] reading configs from: "/home/user/.config/espanso"
10:21:01 [daemon(107485)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
10:21:01 [daemon(107485)] [INFO] using runtime dir: "/home/user/.cache/espanso"
10:21:01 [daemon(107485)] [INFO] system info: Fedora Linux v37 - kernel: 6.1.7-200.fc37.x86_64
10:21:01 [daemon(107485)] [INFO] watching for changes in path: "/home/user/.config/espanso"
10:21:01 [daemon(107485)] [INFO] espanso version: 2.2.1
10:21:01 [daemon(107485)] [INFO] spawning the worker process...
10:21:01 [daemon(107485)] [INFO] binded to IPC unix socket: /home/user/.cache/espanso/espansodaemonv2.sock
10:21:01 [worker(107492)] [INFO] reading configs from: "/home/user/.config/espanso"
10:21:01 [worker(107492)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
10:21:01 [worker(107492)] [INFO] using runtime dir: "/home/user/.cache/espanso"
10:21:01 [worker(107492)] [INFO] system info: Fedora Linux v37 - kernel: 6.1.7-200.fc37.x86_64
10:21:01 [worker(107492)] [INFO] binded to IPC unix socket: /home/user/.cache/espanso/espansoworkerv2.sock
10:21:01 [worker(107492)] [INFO] using WaylandAppInfoProvider
10:21:01 [worker(107492)] [INFO] monitoring the status of the daemon process
10:21:01 [worker(107492)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de+nodeadkeys, V=, O=]
10:21:01 [worker(107492)] [INFO] using EVDEVSource
10:21:01 [worker(107492)] [ERROR] thread 'detect thread' panicked at 'unable to create xkb keymap: could not create xkb keymap': espanso-detect/src/evdev/mod.rs:114
10:21:01 [worker(107492)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
10:21:01 [worker(107492)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
10:21:01 [worker(107492)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
10:21:01 [daemon(107485)] [ERROR] received unexpected exit code from worker 101, exiting
```

**Setup information**
- OS: What OS are you using?
*Fedora 38*

- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
*espanso 2.2.1*

**Comment by morgan-dgk** [comment]
I suspect this is similar to #1890.

Is the layout `de+nodeadkeys` a system default? On my system, the german keyboard with no deadkeys would be specified as `[R=, M=, L=de, V=nodeadkeys, O=]`. 

Espanso launches correctly with the following in my config file:

```
keyboard_layout: 
  layout: "de"
  variant: "nodeadkeys"
```

**Comment by karottenreibe** [comment]
I ran into the same problem until I realized that I had put this:

```
keyboard_layout:
  layout: "de"
  variant: "neo"
```

Into the wrong config file (match/base.yml instead of config/default.yml).
Putting it into config/default.yml fixes the problem.
