### ISSUE TITLE
espanso won't start

### ISSUE THREAD

**Issue by pgn2100** [federico-terzi/espanso#1887]
espanso stopped working as of late and when i used the espanso log command this is what i got , sorry if it's a simple issue or a user error since am not familiar with programming and codes
`
14:35:22 [daemon(60989)] [INFO] reading configs from: "/home/pgn/.config/espanso"

14:35:22 [daemon(60989)] [INFO] reading packages from: "/home/pgn/.config/espanso/match/packages"
14:35:22 [daemon(60989)] [INFO] using runtime dir: "/home/pgn/.cache/espanso"
14:35:22 [daemon(60989)] [INFO] system info: Nobara Linux v39 - kernel: 6.7.6-201.fsync.fc39.x86_64
14:35:22 [daemon(60989)] [INFO] watching for changes in path: "/home/pgn/.config/espanso"
14:35:22 [daemon(60989)] [INFO] espanso version: 2.2.0
14:35:22 [daemon(60989)] [INFO] spawning the worker process...
14:35:22 [daemon(60989)] [INFO] binded to IPC unix socket: /home/pgn/.cache/espanso/espansodaemonv2.sock
14:35:22 [worker(60999)] [INFO] reading configs from: "/home/pgn/.config/espanso"
14:35:22 [worker(60999)] [INFO] reading packages from: "/home/pgn/.config/espanso/match/packages"
14:35:22 [worker(60999)] [INFO] using runtime dir: "/home/pgn/.cache/espanso"
14:35:22 [worker(60999)] [INFO] system info: Nobara Linux v39 - kernel: 6.7.6-201.fsync.fc39.x86_64
14:35:22 [worker(60999)] [INFO] binded to IPC unix socket: /home/pgn/.cache/espanso/espansoworkerv2.sock
14:35:22 [worker(60999)] [INFO] using WaylandAppInfoProvider
14:35:22 [worker(60999)] [INFO] monitoring the status of the daemon process
14:35:22 [worker(60999)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
14:35:22 [worker(60999)] [INFO] using EVDEVSource
14:35:22 [worker(60999)] [INFO] Querying modifier status...
14:35:22 [worker(60999)] [ERROR] thread 'detect thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }': espanso-detect/src/evdev/sync/wayland.rs:193

14:35:22 [worker(60999)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
14:35:22 [worker(60999)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
14:35:22 [worker(60999)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
14:35:22 [daemon(60989)] [ERROR] received unexpected exit code from worker 101, exiting`

**Comment by smeech** [comment]
Have you updated or recompiled lately? The file "espanso-detect/src/evdev/sync/wayland.rs" was amongst those receiving multiple changes three days ago, although the latest change on line 193 seems to be no more than removal of some spaces.
@AucaCoyan might have some insight as to whether this commit might break or fix your problem.

**Comment by pgn2100** [comment]
did not , should i recompile it ?

**Comment by smeech** [comment]
> did not , should i recompile it ?

I'd discuss it with @AucaCoyan first - he's often on the Discord server.

**Comment by AucaCoyan** [comment]
Hi! I'm here. No issue is dumb at all!
What version are you using? because the changes on dev are not released to production yet. Did you compiled from the latest `dev` commit?

**Comment by pgn2100** [comment]
don't think so i compile it once , quite a while ago using the installation guide on the website since i use wayland , the version is 2.2.0

**Comment by AucaCoyan** [comment]
Allright! So this is the prod version. I don't know what is causing it yet, but we can investigate 👍🏼

**Comment by morgan-dgk** [comment]
This is a weird error to see here. My guess is there is something going wrong with the connection to the wayland server.

**Comment by AucaCoyan** [comment]
We had a fix for many wayland issues in the PR #1901 , you can download the artifact here:
https://github.com/espanso/espanso/actions/runs/8487368671/artifacts/1370945517

If you want a different version, you can go to the Action run and scroll all the way down, and you see this:
![image](https://github.com/espanso/espanso/assets/30557287/58caa836-0422-4981-8933-b763926544cd)

The `Ubuntu-Debian` may be a fix to your issue, can you try it? ✋🏼

**Comment by pgn2100** [comment]
sorry for the inconvenience but i use nobara linux , it's based on fedora

**Comment by AucaCoyan** [comment]
Oh! Sorry, my guess was wrong. Then you should use the .AppImage from the artifacts..... _if we had compiled them before_ 😭 
I'll explain: normally we use AppImage for X11, but we don't have a process to have the AppImage for Wayland.
It is possible to compile it and make an AppImage, but it is available in the CI.

If you are adventurous and you want to compile it yourself, you can download the code, follow Compilation.md and pass the command
_edit: just one_ `--`
```
cargo make --env NO_X11=true --profile release -- create-app-image
```

We definitely need some improvement over this, because Wayland is too focused on the debian-based distros, but unreleased when we merge PRs into `dev` or `main`

**Comment by pgn2100** [comment]
tried to compile the dev release but failed .
`[cargo-make] INFO - cargo make 0.37.5
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done

[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: --
[cargo-make] INFO - Profile: release
[cargo-make] ERROR - Task -- not found
[cargo-make] WARN - Build Failed.` 
is there a log file i can upload to help you ?

**Comment by AucaCoyan** [comment]
whoops, I made a mistake, its not double `--`, it's
```
cargo make --env NO_X11=true --profile release -- create-app-image
```
sorry!

**Comment by pgn2100** [comment]
tried it and it's working maybe the only issue is that the espanso welcome screen keep popping up even after closing it .
don't know if it's relatable but i tried launching it from /target/linux/AppImage/out/Espanso-x86_64.AppImage

**Comment by AucaCoyan** [comment]
Thank you! Yeah, we have to make a revision about that AppImage build. Over and over more fedora-kind distros are having problems, we should address some official support. Thank you for reporting and testing again!

**Comment by morgan-dgk** [comment]
Is this good to close @AucaCoyan ?

**Comment by AucaCoyan** [comment]
Yep! Thank you @morgan-dgk !
