### ISSUE TITLE
Restart loop with "espanso service register"

### ISSUE THREAD

**Issue by myigita** [federico-terzi/espanso#1888]
I am using Hyprland with NixOS, and after the service is (seemingly) registered espanso is seemingly stuck in a restart loop where every few seconds a "Espanso Sync Tool" window with a rainbow-y image opens for a fraction of a second and closes immediately. I can get it to work with "espanso service start --unmanaged" but the "Espanso Sync Tool" window stays open and I get a "Espanso is already running!" screen which reopens after a few seconds when closed. The log says "unable to call 'wl-paste' binary, please install the wl-clipboard package." even though it is installed and working properly when I try it in terminal. And another interesting thing is the service can't be found with "systemctl status espanso.service" or even in the "systemctl list". And finally when I tried using espanso with KDE or Gnome (both with Wayland) it worked fine for some reason.

**To Reproduce**
1. $ espanso service register
2. Espanso Sync Tool keeps restarting

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
❯ espanso log
19:09:28 [daemon(5116)] [INFO] reading configs from: "/home/yigit/.config/espanso"
19:09:28 [daemon(5116)] [INFO] reading packages from: "/home/yigit/.config/espanso/match/packages"
19:09:28 [daemon(5116)] [INFO] using runtime dir: "/home/yigit/.cache/espanso"
19:09:28 [daemon(5116)] [INFO] system info: NixOS v24.05 - kernel: 6.6.19
19:09:28 [daemon(5116)] [WARN] keyboard layout watcher couldn't determine active layout.
19:09:28 [daemon(5116)] [INFO] watching for changes in path: "/home/yigit/.config/espanso"
19:09:28 [daemon(5116)] [INFO] espanso version: 2.2.1
19:09:28 [daemon(5116)] [INFO] spawning the worker process...
19:09:28 [daemon(5116)] [INFO] binded to IPC unix socket: /home/yigit/.cache/espanso/espansod
aemonv2.sock
19:09:28 [worker(5122)] [INFO] reading configs from: "/home/yigit/.config/espanso"
19:09:28 [worker(5122)] [INFO] reading packages from: "/home/yigit/.config/espanso/match/packages"
19:09:28 [worker(5122)] [INFO] using runtime dir: "/home/yigit/.cache/espanso"
19:09:28 [worker(5122)] [INFO] system info: NixOS v24.05 - kernel: 6.6.19
19:09:28 [worker(5122)] [INFO] binded to IPC unix socket: /home/yigit/.cache/espanso/espansoworkerv2.sock
19:09:28 [worker(5122)] [INFO] using WaylandAppInfoProvider
19:09:28 [worker(5122)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
19:09:28 [worker(5122)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
19:09:28 [worker(5122)] [INFO] monitoring the status of the daemon process
19:09:28 [worker(5122)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
19:09:28 [worker(5122)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
19:09:28 [worker(5122)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
19:09:28 [worker(5122)] [WARN]   initial setup is completed.
19:09:28 [worker(5122)] [INFO] detection module will use this keyboard layout: [R=, M=, L=tr, V=, O=]
19:09:28 [worker(5122)] [INFO] using EVDEVSource
19:09:28 [worker(5122)] [INFO] Querying modifier status...
19:09:28 [worker(5122)] [ERROR] Failed to set cursor
19:09:28 [worker(5122)] [INFO] inject module will use this keyboard layout: [R=, M=, L=tr, V=, O=]
19:09:28 [worker(5122)] [INFO] using EVDEVInjector
19:09:28 [worker(5122)] [INFO] using WaylandFallbackClipboard
19:09:28 [worker(5122)] [ERROR] unable to call 'wl-paste' binary, please install the wl-clipboard package.
19:09:28 [worker(5122)] [ERROR] thread 'engine thread' panicked at 'failed to initialize clipboard module: wl-clipboard binaries are missing': espanso/src/cli/worker/engine/mod.rs:187
19:09:28 [worker(5122)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
19:09:28 [worker(5122)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
19:09:28 [daemon(5116)] [ERROR] received unexpected exit code from worker 101, exiting

**Setup information**
- OS: NixOS
- Version: 2.2.1 (using this pkg: https://github.com/ingbarrozo/espanso)

**Comment by morgan-dgk** [comment]
@myigita have you considered raising this issue in the repo you linked above? I don't know much about Nix packaging, but the [check](https://github.com/espanso/espanso/blob/78df1b704fe2cc5ea26f88fdc443b6ae1df8a989/espanso-clipboard/src/wayland/fallback/mod.rs#L38C1-L48C6) for wl-clipboard is very simple. 

I suspect this may be an issue with the package build.

**Comment by janonymousm** [comment]
I use NixOS with Home Manager, which seems to work at the moment. Might be worth a try. 

Also, I had a lot of trouble trying to use wl-clipboard. It just didn't work. I then looked for alternatives and found [wl-clipboard-rs](https://github.com/YaLTeR/wl-clipboard-rs), which works with the latest commit on the master. Long story short, maybe wl-clipboard-rs is worth a try if you are having trouble with wl-clipboard.

**Comment by ArikRahman** [comment]
I use it purely with Home Manager but encounter the same issue. Looks like this:
NixOS 2.2 is broken on home-manager, does not start properly:
❯ espanso start
espanso started correctly!

~ took 6s
❯ :espanso
:espanso: command not found

~ took 8s
❯ espanso -V
espanso 2.2.1

~
❯ espanso status
espanso is not running

~
❯ espanso start
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
Please try running 'espanso restart' or manually killing all Espanso processes, then try again.

~ took 7s
❯ espanso service register
service file already exists, this operation will overwrite it
creating service file in "/home/arik/.config/systemd/user/espanso.service"
enabling systemd service
service registered correctly!

~
❯ espanso start
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
Please try running 'espanso restart' or manually killing all Espanso processes, then try again.

~ took 5s
❯ espanso stop
espanso is not running!

~
❯ espanso stop
espanso is not running!

~
❯ killall espanso
espanso: no process found

~
❯ espanso start
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
Please try running 'espanso restart' or manually killing all Espanso processes, then try again.
