### ISSUE TITLE
Newbie debian without desktop + X + dwm = journalctl: infinite error loop message

### ISSUE THREAD

**Issue by aloisleclet** [federico-terzi/espanso#2077]
### Description

Hey, I am a newbie, i just installed a debian without gui, then installed x and dwm, and now i am trying to install espanso.
But systemctl is overflowed by this error messages. I don't know where to start to fix this..

Somebody could maybe help me on this  ?

thanks :)

```cli
$ espanso status
   espanso not running
```

```
$ journalctl -b
17:24:29 [daemon(7185)] [INFO] reading configs from: "/home/dev/.config/espanso"
17:24:29 [daemon(7185)] [INFO] reading packages from: "/home/dev/.config/espanso/match/packages"
17:24:29 [daemon(7185)] [INFO] using runtime dir: "/home/dev/.cache/espanso"
17:24:29 [daemon(7185)] [INFO] system info: Debian GNU/Linux v12 - kernel: 6.1.0-25-amd64
17:24:29 [daemon(7185)] [WARN] keyboard layout watcher couldn't determine active layout.
17:24:29 [daemon(7185)] [INFO] watching for changes in path: "/home/dev/.config/espanso"
17:24:29 [daemon(7185)] [INFO] espanso version: 2.2.1
17:24:29 [daemon(7185)] [INFO] spawning the worker process...
17:24:29 [daemon(7185)] [INFO] binded to IPC unix socket: /home/dev/.cache/espanso/espansodaemonv2.sock
17:24:29 [worker(7193)] [INFO] reading configs from: "/home/dev/.config/espanso"
17:24:29 [worker(7193)] [INFO] reading packages from: "/home/dev/.config/espanso/match/packages"
17:24:29 [worker(7193)] [INFO] using runtime dir: "/home/dev/.cache/espanso"
17:24:29 [worker(7193)] [INFO] system info: Debian GNU/Linux v12 - kernel: 6.1.0-25-amd64
17:24:29 [worker(7193)] [INFO] binded to IPC unix socket: /home/dev/.cache/espanso/espansoworkerv2.sock
17:24:29 [worker(7193)] [INFO] using X11AppInfoProvider
17:24:29 [worker(7193)] [INFO] monitoring the status of the daemon process
17:24:29 [worker(7193)] [INFO] using X11Source
17:24:29 [worker(7193)] [ERROR] X11Source destruction cannot be performed, handle is null
17:24:29 [worker(7193)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:140
17:24:29 [worker(7193)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
17:24:29 [worker(7193)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
17:24:30 [daemon(7185)] [ERROR] received unexpected exit code from worker 101, exiting
```

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
Looks very similar to https://github.com/espanso/espanso/issues/1751 and https://github.com/espanso/espanso/issues/929.

Would you see if there is a solution there?
