### ISSUE TITLE
Error on text replacement

### ISSUE THREAD

**Issue by timothyjlaurent** [federico-terzi/espanso#301]
I got this running on Linux Mint with Cinnamon using `espanso -v daemon` but there is this error when a it processes a trigger:

```console
04:17:44 [ INFO] espanso version 0.6.1
04:17:44 [ INFO] using config path: /home/dadmin/.config/espanso
04:17:44 [ INFO] using package path: /home/dadmin/.local/share/espanso/packages
04:17:44 [ INFO] spawning worker process...
04:17:44 [ INFO] Binded to IPC unix socket: /home/dadmin/.local/share/espanso/espanso.sock
04:17:52 [ERROR] thread 'daemon_background' panicked at 'a Display implementation returned an error unexpectedly: Error': /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/string.rs:2165
stack backtrace:
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   2: rust_begin_unwind
             at src/libstd/panicking.rs:378
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at src/libcore/option.rs:1211
   5: <espanso::extension::date::DateExtension as espanso::extension::Extension>::calculate
   6: <espanso::render::default::DefaultRenderer as espanso::render::Renderer>::render_match
   7: <espanso::engine::Engine<S,C,M,U,R> as espanso::matcher::MatchReceiver>::on_match
   8: espanso::matcher::<impl espanso::event::KeyEventReceiver for M>::on_key_event
   9: <espanso::event::manager::DefaultEventManager as espanso::event::manager::EventManager>::eventloop
  10: espanso::worker_background
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  17: start_thread
  18: __clone

```

**Comment by federico-terzi** [comment]
Hey @timothyjlaurent 

This is a very strange error indeed! Does it happen with all matches or only with one in particular?
Would you mind sharing the trigger that caused that crash?

Thanks for your help :)

**Comment by timothyjlaurent** [comment]
Thanks for the quick response - After rebooting, I'm not able to reproduce the issue. I'll close this, thanks, again.

**Comment by federico-terzi** [comment]
No problem! let me know if the problem happens again :)
