### ISSUE TITLE
Espanso not working on MacOS

### ISSUE THREAD

**Issue by xplosionmind** [federico-terzi/espanso#565]
Device: MacBook Pro 13" 2019
OS: MacOS 11.1
Espanso version: 0.7.3

## Issue

I receive a MacOS notification telling me “espanso is running!” but nothing happens when I type text which should be replaced. This doesn't work in any app. It worked before! Then, out of the blue, everything stopped working. In the log there seems to be some error, but I have no idea what it is.

### Notes

- I gave all the necessary permissions (namely Accessibility) in MacOS preferences
- I whitelisted Espanso in every possible app which blocks traffic or scripts

<br>

## Log

```
08:38:48 [ INFO] espanso version 0.7.3
08:38:48 [ INFO] using config path: /Users/xplosionmind/Library/Preferences/espanso
08:38:48 [ INFO] using package path: /Users/xplosionmind/Library/Application Support/espanso/packages
08:38:48 [ INFO] spawning worker process...
08:38:48 [ INFO] Binded to IPC unix socket: /Users/xplosionmind/Library/Application Support/espanso/espanso.sock
08:38:48 [ INFO] initializing worker process...
08:38:48 [ INFO] Status icon already initialized, skipping.
08:38:48 [ INFO] Status icon (disabled) already initialized, skipping.
08:38:48 [ INFO] Initializing EspansoNotifyHelper in /Users/xplosionmind/Library/Application Support/espanso
08:38:48 [ INFO] EspansoNotifyHelper already initialized, skipping.
08:38:48 [ INFO] Binded to IPC unix socket: /Users/xplosionmind/Library/Application Support/espanso/worker.sock
08:38:48 [ INFO] Using modulo at "/usr/local/bin/modulo"
08:38:48 [ERROR] thread 'daemon_background' panicked at 'unable to generate modulo app stub: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': src/ui/modulo/mod.rs:78
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: log_panics::init::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: espanso::ui::modulo::ModuloManager::new
  10: espanso::extension::get_extensions
  11: espanso::worker_background
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::unix::thread::Thread::new::thread_start
  15: _pthread_start

08:38:48 [ INFO] watching for changes in path: /Users/xplosionmind/Library/Preferences/espanso
08:38:50 [ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"': src/context/macos.rs:254
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: log_panics::init::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: espanso::context::macos::keypress_callback
  10: GlobalObserverHandler
  11: _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec
  12: _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec
  13: SendEventToEventTargetWithOptions
  14: _ZL29ToolboxEventDispatcherHandlerP25OpaqueEventHandlerCallRefP14OpaqueEventRefPv
  15: _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec
  16: _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec
  17: SendEventToEventTarget
  18: _DPSNextEvent
  19: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  20: -[NSApplication run]
  21: <espanso::context::macos::MacContext as espanso::context::Context>::eventloop
  22: espanso::main
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::rt::lang_start::{{closure}}
  25: std::rt::lang_start_internal
  26: main

08:38:50 [ERROR] worker process exited with non-zero code: 101, exiting
```

**Comment by federico-terzi** [comment]
Hey @xplosionmind,

Thanks for reporting this issue! I'm wondering whether that could be an issue related to Big Sur (which unfortunately I haven't had the chance to test yet). I'll investigate and let you know! (although I'm not sure when I'll be able to get my hands on a BigSur machine)

Cheers :)

**Comment by federico-terzi** [comment]
@xplosionmind If you run the following on a terminal, do you see a window appear?

```
echo "layout: Hi" | /usr/local/bin/modulo form -i -
```

**Comment by xplosionmind** [comment]
> do you see a window appear?

I get this:
![Screenshot 2021-01-12 at 9 21 41 PM](https://user-images.githubusercontent.com/42862428/104368465-64971400-551c-11eb-8aa1-86c9f140db2b.jpg)

**Comment by federico-terzi** [comment]
@xplosionmind Grea, thank you. At least something is working :) From the log files, it seems to be a permission problem, although this is the first time that I see that happening

**Comment by xplosionmind** [comment]
It's odd indeed… I whitelisted espanso everywhere, and it worked for some time, too! I changed nothing except my config file in the meantime. Could it be the problem? I checked the YAML formatting several times.

**Comment by RMHogervorst** [comment]
Have the same problem this is in my logs

`SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow`

**Comment by RMHogervorst** [comment]
on restart `espanso restart` I get the following message:

```
WARNING: An application is currently using SecureInput and might prevent espanso from working correctly.

APP: loginwindow
PROC: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow

Please close it or disable SecureInput for that application (most apps that use it have a
setting to disable it)
```

**Comment by RMHogervorst** [comment]
I closed a bunch of apps and now it works again. Not sure which one it was that caused the problem

**Comment by xplosionmind** [comment]
> I closed a bunch of apps and now it works again. Not sure which one it was that caused the problem


I tried closing other apps too. Nothing changes. Another log report in the hope that it may bring more clarity concerning what's wrong.

```sh
14:30:29 [ INFO] espanso version 0.7.3
14:30:29 [ INFO] using config path: /Users/xplosionmind/Library/Preferences/espanso
14:30:29 [ INFO] using package path: /Users/xplosionmind/Library/Application Support/espanso/packages
14:30:29 [ INFO] spawning worker process...
14:30:29 [ INFO] Binded to IPC unix socket: /Users/xplosionmind/Library/Application Support/espanso/espanso.sock
14:30:29 [ INFO] initializing worker process...
14:30:29 [ INFO] Status icon already initialized, skipping.
14:30:29 [ INFO] Status icon (disabled) already initialized, skipping.
14:30:29 [ INFO] Initializing EspansoNotifyHelper in /Users/xplosionmind/Library/Application Support/espanso
14:30:29 [ INFO] EspansoNotifyHelper already initialized, skipping.
14:30:29 [ INFO] Binded to IPC unix socket: /Users/xplosionmind/Library/Application Support/espanso/worker.sock
14:30:29 [ INFO] Using modulo at "/usr/local/bin/modulo"
14:30:29 [ERROR] thread 'daemon_background' panicked at 'unable to generate modulo app stub: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': src/ui/modulo/mod.rs:78
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: log_panics::init::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: espanso::ui::modulo::ModuloManager::new
  10: espanso::extension::get_extensions
  11: espanso::worker_background
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::unix::thread::Thread::new::thread_start
  15: _pthread_start

14:30:29 [ INFO] watching for changes in path: /Users/xplosionmind/Library/Preferences/espanso
14:30:32 [ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"': src/context/macos.rs:221
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: log_panics::init::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: espanso::context::macos::keypress_callback
  10: GlobalObserverHandler
  11: _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec
  12: _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec
  13: SendEventToEventTargetWithOptions
  14: _ZL29ToolboxEventDispatcherHandlerP25OpaqueEventHandlerCallRefP14OpaqueEventRefPv
  15: _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec
  16: _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec
  17: SendEventToEventTarget
  18: _DPSNextEvent
  19: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  20: -[NSApplication run]
  21: <espanso::context::macos::MacContext as espanso::context::Context>::eventloop
  22: espanso::main
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::rt::lang_start::{{closure}}
  25: std::rt::lang_start_internal
  26: main

14:30:32 [ERROR] worker process exited with non-zero code: 101, exiting
```

**Comment by federico-terzi** [comment]
@xplosionmind From the log, the configuration file is loaded correctly. What's interesting is that the `modulo` app stub creation fails. In a nutshell, espanso at startup creates an `.app` wrapper for modulo in the `/Users/xplosionmind/Library/Application Support/espanso`. This is somehow failing, could you please see if inside that directory you see a `Modulo.app`? If so, try to delete it and restart espanso, perhaps that might solve the issue :)

@RMHogervorst your problem is related to SecureInput, if you are interested here there is a small explanation: https://espanso.org/docs/configuration/#macos-notification-for-secureinput

Cheers :)

**Comment by xplosionmind** [comment]
That's it! Now it's working. I stopped espanso, deleted /Users/xplosionmind/Library/Application Support/espanso/Modulo.app and started espanso again.

Thanks a lot!
T

**Comment by federico-terzi** [comment]
@xplosionmind Glad to hear that! Let me know if that happens again

**Comment by ErichDonGubler** [comment]
The link for MacOS' `SecureInput` above has rotted; new docs. link: https://espanso.org/docs/troubleshooting/secure-input/

**Comment by clemwo** [comment]
I'm having a similar issue where espanso says that it's running but its not working on MacOS. 

I think it always happens when I switch user accounts on Mac (which both have espanso). 

For me simply running
`pkill espanso && open -a espanso` works to quit and restart espanso.  

Not optimal but fast enough that Im not really bothered to look for a different solution.

**Comment by smeech** [comment]
Yes, something of this sort is usually the workaround for Espanso use on multi-account machines. I think there are a few Open issues of relevance.

**Comment by bigplayer-ai** [comment]
same
