### ISSUE TITLE
espanso-git aur package no longer builds:

### ISSUE THREAD

**Issue by xircon** [federico-terzi/espanso#817]
```
==> Starting package()...
install: cannot stat 'target/release/espanso': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
:: Unable to build espanso-git - makepkg exited with code: 4
```
@Scrumplex any ideas?

**Comment by jwliles** [comment]
When I tried to install just now I received the following message
```
error: failed to run custom build command for `espanso-modulo v0.1.0 (/home/jwl/.cache/yay/espanso-git/src/espanso/espanso-modulo)`

Caused by:
process didn't exit successfully: `/home/jwl/.cache/yay/espanso-git/src/espanso/target/release/build/espanso-modulo-08deab6d9ec245f8/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'wxWidgets is not installed, as `wx-config` cannot be executed', espanso-modulo/build.rs:439:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
thread 'main' panicked at 'cargo build failed', 7XFwkBcBnu.rs:94:5
stack backtrace:
0:     0x558d91d1c6fc - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
1:     0x558d91d1c6fc - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:     0x558d91d1c6fc - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
3:     0x558d91d1c6fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
4:     0x558d91d3a93c - core::fmt::write::h31b9cd1bedd7ea38
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
5:     0x558d91d1a5f5 - std::io::Write::write_fmt::h1fdf66f83f70913e
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
6:     0x558d91d1e4a0 - std::sys_common::backtrace::_print::he7ac492cd19c3189
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
7:     0x558d91d1e4a0 - std::sys_common::backtrace::print::hba20f8920229d8e8
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
8:     0x558d91d1e4a0 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
9:     0x558d91d1e057 - std::panicking::default_hook::hf1afb64e69563ca8
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
10:     0x558d91d1eb54 - std::panicking::rust_panic_with_hook::h02231a501e274a13
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
11:     0x558d91d00e95 - std::panicking::begin_panic::{{closure}}::h9e18e0e604b29bf2
12:     0x558d91d00e54 - std::sys_common::backtrace::__rust_end_short_backtrace::h6fec443b1709a93f
13:     0x558d91cfc1ec - std::panicking::begin_panic::h0f39a9f49183e367
14:     0x558d91d006e5 - _7xfwkbcbnu_a6e2f269aaae7bc5ccdc819e::main::h00c8cbaad0f379b0
15:     0x558d91d00e63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4746fe3a6f6312fd
16:     0x558d91cff479 - std::rt::lang_start::{{closure}}::h99ca325bd0a59a0d
17:     0x558d91d1f05a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
18:     0x558d91d1f05a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
19:     0x558d91d1f05a - std::panicking::try::h675520ee37b0fdf7
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
20:     0x558d91d1f05a - std::panic::catch_unwind::h803430ea0284ce79
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
21:     0x558d91d1f05a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
22:     0x558d91d1f05a - std::panicking::try::do_call::hf60f106700df94b2
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
23:     0x558d91d1f05a - std::panicking::try::hb2022d2bc87a9867
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
24:     0x558d91d1f05a - std::panic::catch_unwind::hbf801c9d61f0c2fb
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
25:     0x558d91d1f05a - std::rt::lang_start_internal::hdd488b91dc742b96
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
26:     0x558d91d00862 - main
27:     0x7f2c2c28db25 - __libc_start_main
28:     0x558d91cfeb5e - _start
29:                0x0 - <unknown>
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.
==> ERROR: A failure occurred in build().
Aborting...
-> error making: espanso-git
```
Running
```
yay -S wxgtk3
```
is all I needed to do to get the aur package to install.

This is my system

![system-info](https://user-images.githubusercontent.com/13804903/140625067-86633b57-0cc8-4f73-8254-664253fe13b4.png)

**Comment by federico-terzi** [comment]
Hey @jwliles,

I'm sorry you experienced this problem! If you run these commands in the terminal, what do you see?

```
wx-config --version
wx-config-gtk3 --version
```

Yesterday I've shipped a fix for #840, so there's a good chance you'll be able to run the installation successfully now :)

Let me know if that helps

Cheers :)

**Comment by jwliles** [comment]
![wx-config](https://user-images.githubusercontent.com/13804903/140656019-b79e75db-3163-475f-a12e-c4aacba9ab3f.png)

After installing `wxgtk3` yesterday, Espanso has worked flawlessly.

**Comment by federico-terzi** [comment]
@jwliles Nice! Thanks :)

**Comment by Scrumplex** [comment]
Oh my god how have I missed this thread for two weeks. The fix would have taken like 2 minutes. Well.. :D

**Comment by Scrumplex** [comment]
Both issues are fixed now. wxgtk3 is now added as a build and runtime dependency and the `cargo make` command has the correct order now

**Comment by federico-terzi** [comment]
@Scrumplex Thank you so much! :)
