### ISSUE TITLE
Espanso not starting on F34 Wayland KDE

### ISSUE THREAD

**Issue by reesericci** [federico-terzi/espanso#848]
Whenever I try to start espanso it gives me this log output:
```
22:17:21 [daemon(14122)] [INFO] reading configs from: "/home/reesericci/.config/espanso"
22:17:21 [daemon(14122)] [INFO] reading packages from: "/home/reesericci/.config/espanso/match/packages"
22:17:21 [daemon(14122)] [INFO] using runtime dir: "/home/reesericci/.cache/espanso"
22:17:21 [daemon(14122)] [INFO] watching for changes in path: "/home/reesericci/.config/espanso"
22:17:21 [daemon(14122)] [INFO] espanso version: 2.0.4-alpha
22:17:21 [daemon(14122)] [INFO] spawning the worker process...
22:17:21 [daemon(14122)] [INFO] binded to IPC unix socket: /home/reesericci/.cache/espanso/espansodaemonv2.sock
22:17:21 [daemon(14122)] [WARN] keyboard layout watcher couldn't determine active layout.
22:17:21 [worker(14129)] [INFO] reading configs from: "/home/reesericci/.config/espanso"
22:17:21 [worker(14129)] [INFO] reading packages from: "/home/reesericci/.config/espanso/match/packages"
22:17:21 [worker(14129)] [INFO] using runtime dir: "/home/reesericci/.cache/espanso"
22:17:21 [worker(14129)] [INFO] binded to IPC unix socket: /home/reesericci/.cache/espanso/espansoworkerv2.sock
22:17:21 [worker(14129)] [INFO] using WaylandAppInfoProvider
22:17:21 [worker(14129)] [INFO] detection module will use this keyboard layout: [R=, M=, L=en, V=, O=]
22:17:21 [worker(14129)] [INFO] monitoring the status of the daemon process
22:17:21 [worker(14129)] [INFO] using EVDEVSource
22:17:21 [worker(14129)] [ERROR] thread 'detect thread' panicked at 'unable to create xkb keymap: could not create xkb keymap': espanso-detect/src/evdev/mod.rs:113
22:17:21 [worker(14129)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:123
22:17:21 [worker(14129)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
22:17:21 [worker(14129)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:155
22:17:21 [daemon(14122)] [ERROR] received unexpected exit code from worker 101, exiting
```

I added myself to the input group, added the keyboard layout in the config, and ran `sudo setcap "cap_dac_override+p" /usr/local/bin/espanso` to get to this point. (before I had perms errors with evdev)

Breakout from #287

**Comment by federico-terzi** [comment]
Hey @reesericci,

Thanks for reporting this issue! What keyboard layout are you using?

Cheers :)

**Comment by reesericci** [comment]
en

**Comment by reesericci** [comment]
it didn't auto-detect

**Comment by reesericci** [comment]
I fixed it by setting the keyboard layout to "us" instead of "en"

**Comment by federico-terzi** [comment]
@reesericci Intersting, glad you figured that out!

**Comment by reesericci** [comment]
@federico-terzi There should be docs listing out all the keyboard_layout options in case it doesn't get auto-detected.

**Comment by federico-terzi** [comment]
@reesericci Thank you for the feedback! The docs are still lacking, we are working hard to get them ready for the v2 :)
