### ISSUE TITLE
Following installation - timeout on service occurs

### ISSUE THREAD

**Issue by dlbradford** [federico-terzi/espanso#929]
Following the directions for installing on Linux X11 via snap image:
https://espanso.org/docs/next/install/linux/
"espanso start
unable to start service: timed out"

Is there a more detailed log or some method to gain insight as to what is the problem?

**Comment by dlbradford** [comment]
Further looking into system logs shows this:
/var/log/kern.log:Jan  7 12:17:13 pop-os kernel: [61918.969432] traps: espanso[93926] trap int3 ip:7fc204c3466f sp:7ffeda483f60 error:0 in libglib-2.0.so.0.6800.4[7fc204bf5000+8d000]

**Comment by federico-terzi** [comment]
Hey @dlbradford,

Thanks for reporting this issue! This is strange, it might be related to the problem we had with the AppImage last week #900.
Could you please run the following command in a terminal, leave it running for 10 seconds and then post the output here?

```
espanso -vv worker
```

Cheers :)

**Comment by nocibambi** [comment]
I also had a bit similar timeout, but with a different error message.

```
an instance of legacy espanso is running, please terminate it, otherwise the new version cannot start
```

Worker output:

```log
$ espanso -vv worker
14:11:31 [worker(748404)] [DEBUG] (1) espanso_path: detected config directory in $HOME/.config/espanso
;14:11:31 [worker(748404)] [DEBUG] (1) espanso_path: detected legacy runtime dir: "/home/user/.local/share/espanso"
14:11:31 [worker(748404)] [DEBUG] (1) espanso_path: detected legacy packages dir: "/home/user/.local/share/espanso/packages"
14:11:31 [worker(748404)] [INFO] reading configs from: "/home/user/.config/espanso"
14:11:31 [worker(748404)] [INFO] reading packages from: "/home/user/.local/share/espanso/packages"
14:11:31 [worker(748404)] [INFO] using runtime dir: "/home/user/.local/share/espanso"
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'alacritty_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'emacs_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'gedit_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'generic_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'kitty_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'konsole_terminal_x11' patch
:14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'libreoffice_writer_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'simple_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'simple_terminal_2_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'terminator_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'termite_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'thunderbird_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'tilix_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'urxvt_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'xterm_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'yakuake_terminal_x11' patch
14:11:31 [worker(748404)] [DEBUG] (1) espanso::patch::config_store: enabled 'virtualbox_x11' patch
14:11:31 [worker(748404)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
14:11:31 [worker(748404)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
14:11:31 [worker(748404)] [DEBUG] (1) espanso::cli::worker: starting with start-reason = None
14:11:31 [worker(748404)] [ERROR] an instance of legacy espanso is running, please terminate it, otherwise the new version cannot start
```

Environment: Ubuntu 20.04

```sh
$ espanso -V
espanso 2.1.4-beta
$ espanso status
espanso is not running
$ espanso start
unable to start service: timed out
$ espanso restart
espanso is not running!
unable to start service: timed out
```

**Comment by SamuelSwartzberg** [comment]
@nocibambi Maybe this is a little trivial (and I am by no means a shell/*nix expert), but have you tried `killall espanso`?

**Comment by nocibambi** [comment]
@SamuelSwartzberg Well, it wasn't trivial for me! :sweat_smile: Yes, this stopped the 'legacy' version. Thanks a lot.

However, when I tried to start espanso, I received a popup offering me to migrate my old config but failed to do so (someone else [already reported it](https://github.com/federico-terzi/espanso/issues/1051)).

**Comment by rickalex21** [comment]
Same problem here, was working fine then I used Wayland and switched back to X11 and now it does not work.

**Comment by channingwalton** [comment]
This just happened to me too. I fixed it by killing the espanso processes and starting espanso again.

**Comment by ewoks** [comment]
hey @federico-terzi I know it's a while but stumble upon the same issue just after installation and not sure how to proceed 
X11
v2.1.8
Kernel 4.18.0

The`espanso -vv worker` logs:
```
[worker(51678)] [ERROR] X11Source destruction cannot be performed, handle is null
[worker(51678)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139
[worker(51678)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
[worker(51678)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
```
does that help?

**Comment by enbugger** [comment]
I'm facing the same issue as @ewoks mentioned on Ubuntu 22.04.1, session type x11. 
Removal of 2.1.8 and installation of 2.2.1 didn't help

**Comment by ewoks** [comment]
still without solution on my side

**Comment by jarrodharvey** [comment]
I'm getting the exact same errors as @ewoks when I run `espanso -vv worker`.

**Comment by ewoks** [comment]
@federico-terzi are there maybe some updates on this?

**Comment by dwbfox** [comment]
Still happening, it's core dumping on start

```
[Fri May 31 13:22:27 2024] traps: espanso[40429] trap int3 ip:7ac83e320fc1 sp:7ffdad7688a0 error:0 in libglib-2.0.so.0.5600.4[7ac83e2cf000+114000]
[Fri May 31 13:22:30 2024] traps: espanso[40453] trap int3 ip:76e5b8b72fc1 sp:7ffd92ce0c00 error:0 in libglib-2.0.so.0.5600.4[76e5b8b21000+114000]
[Fri May 31 13:22:34 2024] traps: espanso[40476] trap int3 ip:7789c2bacfc1 sp:7ffd488f10d0 error:0 in libglib-2.0.so.0.5600.4[7789c2b5b000+114000]
[Fri May 31 13:22:37 2024] traps: espanso[40513] trap int3 ip:715313b5cfc1 sp:7fff0820aa90 error:0 in libglib-2.0.so.0.5600.4[715313b0b000+114000]
```

**Comment by ewoks** [comment]
I gave up on waiting fix as I couldn't understand where is the issue exactly on Fedora 40 Wayland.
However, I compiled the v2.2.1 by [following the docs](https://espanso.org/docs/install/linux/#wayland-compile) and made it work.

**Comment by smeech** [comment]
> I gave up on waiting fix as I couldn't understand where is the issue exactly on Fedora 40 Wayland. However, I compiled the v2.2.1 by [following the docs](https://espanso.org/docs/install/linux/#wayland-compile) and made it work.

Some of these issues have been fixed in the _next_ release, which is effectively what you're picking up when you compile.

**Comment by Vistaus** [comment]
I just experienced this issue on CachyOS (based on Arch) after the latest updates. The only way to start Espanso now is by using espanso launcher
