### ISSUE TITLE
Espanso crashes on Wayland if keyboard layout is set to "us+altgr-intl"

### ISSUE THREAD

**Issue by 73** [federico-terzi/espanso#953]
**Describe the bug**
espanso 2.1.3-alpha wayland package crashes at startup on Ubuntu 21.10 

**To Reproduce**
1. Follow install procedure at https://espanso.org/docs/next/install/linux/#deb-wayland
2. Start:
```
🠶 espanso start
unable to start service: timed out
```

**Expected behavior**
I expect Espanso to start.

**Logs**
```
🠶  espanso log
10:51:05 [daemon(108808)] [INFO] reading configs from: "/home/user/.config/espanso"
10:51:05 [daemon(108808)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
10:51:05 [daemon(108808)] [INFO] using runtime dir: "/home/user/.local/share/espanso"
10:51:05 [daemon(108808)] [INFO] watching for changes in path: "/home/user/.config/espanso"
10:51:05 [daemon(108808)] [INFO] espanso version: 2.1.3-alpha
10:51:05 [daemon(108808)] [INFO] spawning the worker process...
10:51:05 [daemon(108808)] [INFO] binded to IPC unix socket: /home/user/.local/share/espanso/espansodaemonv2.sock
10:51:05 [worker(108817)] [INFO] reading configs from: "/home/user/.config/espanso"
10:51:05 [worker(108817)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
10:51:05 [worker(108817)] [INFO] using runtime dir: "/home/user/.local/share/espanso"
10:51:05 [worker(108817)] [INFO] binded to IPC unix socket: /home/user/.local/share/espanso/espansoworkerv2.sock
10:51:05 [worker(108817)] [INFO] using WaylandAppInfoProvider
10:51:05 [worker(108817)] [INFO] monitoring the status of the daemon process
10:51:05 [worker(108817)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us+altgr-intl, V=, O=]
10:51:05 [worker(108817)] [INFO] using EVDEVSource
10:51:05 [worker(108817)] [ERROR] thread 'detect thread' panicked at 'unable to create xkb keymap: could not create xkb keymap': espanso-detect/src/evdev/mod.rs:114
10:51:05 [worker(108817)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
10:51:05 [worker(108817)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
10:51:05 [worker(108817)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
10:51:05 [daemon(108808)] [ERROR] received unexpected exit code from worker 101, exiting
```

**Setup information**
- OS: Ubuntu 21.10. GNOME Wayland Session
- Version: espanso 2.1.3-alpha

**Comment by federico-terzi** [comment]
Hey @73,

Thanks for reporting this issue! I'll investigate

Cheers :)

**Comment by 73** [comment]
Hit me up if I can help / test more.

**Comment by federico-terzi** [comment]
@73 When you have the chance, could you please try adding the following to your `$CONFIG/config/default.yml` file and check if Espanso starts? 

```yaml
keyboard_layout:
  layout: "us"
```

Thanks :)

**Comment by 73** [comment]
I have two Keyboard Layouts. `US International` and `DE` (Built-in Keyboard). It starts with the `DE`Keyboard set. However, expansion is not working and `espanso log`shows:
``` 
🠶  espanso log
12:22:40 [daemon(51587)] [INFO] reading configs from: "/home/user/.config/espanso"
12:22:40 [daemon(51587)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
12:22:40 [daemon(51587)] [INFO] using runtime dir: "/home/user/.local/share/espanso"
12:22:40 [daemon(51587)] [INFO] watching for changes in path: "/home/user/.config/espanso"
12:22:40 [daemon(51587)] [INFO] espanso version: 2.1.3-alpha
12:22:40 [daemon(51587)] [INFO] spawning the worker process...
12:22:40 [daemon(51587)] [INFO] binded to IPC unix socket: /home/user/.local/share/espanso/espansodaemonv2.sock
12:22:40 [worker(51596)] [INFO] reading configs from: "/home/user/.config/espanso"
12:22:40 [worker(51596)] [INFO] reading packages from: "/home/user/.config/espanso/match/packages"
12:22:40 [worker(51596)] [INFO] using runtime dir: "/home/user/.local/share/espanso"
12:22:40 [worker(51596)] [INFO] binded to IPC unix socket: /home/user/.local/share/espanso/espansoworkerv2.sock
12:22:40 [worker(51596)] [INFO] using WaylandAppInfoProvider
12:22:40 [worker(51596)] [INFO] monitoring the status of the daemon process
12:22:40 [worker(51596)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de, V=, O=]
12:22:40 [worker(51596)] [INFO] using EVDEVSource
12:22:40 [worker(51596)] [INFO] Querying modifier status...
12:22:40 [worker(51596)] [INFO] inject module will use this keyboard layout: [R=, M=, L=de, V=, O=]
12:22:40 [worker(51596)] [INFO] using EVDEVInjector
12:22:40 [worker(51596)] [INFO] using WaylandFallbackClipboard
12:22:40 [worker(51596)] [ERROR] unable to call 'wl-paste' binary, please install the wl-clipboard package.
12:22:40 [worker(51596)] [ERROR] thread 'engine thread' panicked at 'failed to initialize clipboard module: wl-clipboard binaries are missing': espanso/src/cli/worker/engine/mod.rs:184
12:22:40 [worker(51596)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
12:22:40 [worker(51596)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
12:22:41 [daemon(51587)] [ERROR] received unexpected exit code from worker 101, exiting
```

**Comment by federico-terzi** [comment]
@73 Thanks! This looks more promising. Could you please install `wl-clipboard` with:

```
sudo apt install wl-clipboard
```

And then try again?

I've created an issue #956 to include this dependency in the deb package, thanks!

**Comment by 73** [comment]
Works for `de` now. Not sure about the international layout though (can not test for some time). I mark this as solved for now. Thank @federico-terzi

**Comment by federico-terzi** [comment]
@73 Nice! I'll reopen the issue to investigate further, I suspect the "us+altgr-intl" layout might need some conversion to be accepted by Espanso :)

**Comment by KyleRConway** [comment]
For what it's worth, I'm on Fedora Linux with Wayland, and I'm getting a similar issue (also 2 keyboard layouts: English US and English Dvorak).

```
10:20:03 [worker(1311093)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us+dvorak, V=, O=]
10:20:03 [worker(1311093)] [INFO] using EVDEVSource
10:20:03 [worker(1311093)] [ERROR] thread 'detect thread' panicked at 'unable to create xkb keymap: could not create xkb keymap': espanso-detect/src/evdev/mod.rs:114
```

Running `espanso start` on the English US layout will result in `espanso is already running!`

Doing the same when using English Dvorak results in `unable to start service: timed out` with the log output above.

**Comment by alexlyzhov** [comment]
Adding this to `~/.config/default.yml` has helped me for colemak:

```
keyboard_layout:
  layout: us
  variant: colemak
```

**Comment by ryancwalsh** [comment]
I use espanso on Windows, Mac, and Ubuntu. It has been working well on all 3 til recently. 

After I recently reinstalled my Ubuntu OS (and espanso), I've started having some problems there. 

I see the log say `10:08:58 [daemon(866072)] [WARN] keyboard layout watcher couldn't determine active layout.`

I don't know whether the log also said that back when it was _working_ on Ubuntu though.

How can I proactively set the appropriate `keyboard_layout` config?

`localectl status` shows:

   System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

So I would assume:

```
keyboard_layout:
  layout: "us"
```

But how do I know the correct variant, etc?  Thanks.

(And I'm happy to write this as a separate new issue if that would be better.)

cc @alexlyzhov
